### ISSUE TITLE
Add support for Linux capabilities in keyframe.yml 

### ISSUE THREAD

**Issue by mikesimos** [resin-io-modules/keyfctl#17]
Adding support for [Linux capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html) configuration would be great.
Sample output for k8s target:
``` 
    securityContext:
      capabilities:
        add: 
          - NET_ADMIN
          - SYS_TIME
```
